// css/AmenitiesStyles.js
import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fff',
  },
  navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'android' ? 50 : 60,
    paddingHorizontal: 25,
    paddingBottom: 15,
    backgroundColor: '#fff',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    zIndex: 10,
  },
  navTitle: {
    marginLeft: 15,
    fontSize: 24,
    fontWeight: '600',
    fontFamily: 'PlayfairDisplay',
    color: '#2c3e50',
    letterSpacing: 0.5,
  },
  container: {
    padding: 25,
    backgroundColor: '#fff',
    flexGrow: 1,
  },
  goldLine: {
    height: 4,
    width: 100,
    backgroundColor: '#C8A951',
    alignSelf: 'center',
    marginBottom: 35,
    borderRadius: 2,
    shadowColor: '#C8A951',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  heading: {
    fontSize: 26,
    fontWeight: '600',
    fontFamily: 'PlayfairDisplay',
    marginBottom: 25,
    textAlign: 'center',
    color: '#2c3e50',
    letterSpacing: 0.5,
  },
  section: {
    marginBottom: 30,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: 15,
    fontFamily: 'PlayfairDisplay',
    letterSpacing: 0.5,
  },
  sectionDesc: {
    fontSize: 16,
    lineHeight: 24,
    color: '#555',
    textAlign: 'left',
    fontFamily: 'PlayfairDisplay',
  },
  foodHeading: {
    textAlign: 'center',
    marginTop: 15,
    fontWeight: '600',
    color: '#C8A951',
  },
  poolGrid: {
    flexDirection: 'column',
    gap: 20,
    marginBottom: 20,
  },
  poolBox: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 0,
    marginBottom: 0,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  poolImage: {
    width: '100%',
    height: 200,
    marginBottom: 0,
  },
  poolLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c3e50',
    marginTop: 15,
    marginBottom: 8,
    textAlign: 'center',
    paddingHorizontal: 15,
    fontFamily: 'PlayfairDisplay',
  },
  poolDesc: {
    fontSize: 15,
    color: '#666',
    textAlign: 'center',
    paddingHorizontal: 15,
    paddingBottom: 20,
    fontFamily: 'PlayfairDisplay',
    lineHeight: 22,
  },
});

export default styles;